### ISSUE TITLE
Auth by SMS

### ISSUE THREAD

**Issue by jcorry** [jcorry/morellis#43]
I want users to be able to interact with the system as frictionless as possible. One way of doing this is to allow users to log in with no password, but simply by providing their phone number. Users who are created and authenticated this way will have their permissions limited to `flavor|store|ingredient:read` `self:read`, `self:write`.

Users with these permissions should be able to:
- View Stores
- View Flavors
- Manage their profile
- Manage their notification preferences

# Basic Flow
![drawing](https://docs.google.com/drawings/d/e/2PACX-1vSiB0hH6PCZLUaw3wkDY7mSucToKPwot5TRLzmPqK4Zxdlc2zp1p3Tb8St_kYTWcWxB7IUglRVS6jMV/pub?w=745&h=530)
# Endpoints Required

## POST /webhook/v1/sms/auth
```
body {
    MessageSid: string,
    From: phone number,
    Body: message body
}
```
Generates a [single-use token](https://github.com/teris-io/shortid) that can be used for authentication. If other tokens exist for the user, they are marked as expired/used. Only one non-expired token can exist at a time.

- Look up the user identified by phone number, if none found create the user
- Get the user's auth token, if none exists, create one
- Send the user the URL they can auth at

This endpoint will need to be called from non-authenticated users. It should be rate-limited and should prevent abuse by:
- Look at previously generated tokens for the request phone number, if there are 5 in the last hour, refuse the request and log the IP address that made the request
- Alert administrator (?)

If no user exists with the phone number, they are created with the necessary permissions and an `active` status.

Response
```
{
    "token": SINGLE_USE_TOKEN,
    "phone": REQUESTING_PHONE_NUMBER,
    "url": "https://host.com/api/v1/auth/{SINGLE_USE_TOKEN}"
}
```

## POST /api/v1/auth/{token}

Validates a token that was issued to a phone number.

If the validation is successful and the token and phone number match a User, a valid JWT for that User will be issued in response.

- Rate limit requests to this endpoint

Request Body
```
{
    "phone": A_VALID_PHONE_NUMBER
}
```

Response Body
```
{
    "token": VALID_JWT,
    "expires": JWT_EXPIRATION_TIME
}
```
# DB Schema

Auth tokens will be stored in Redis. The key is the auth token, the value is the user's ID. Auth tokens will have an expiration time of 5-10 min.

```
> set auth-token:TOKEN USER_ID
> OK
> expire auth-token:TOKEN 300
> 1
```

When an auth request is generated (by Twilio web hook)
- The user is looked up by phone number (or created with permissions).
- An auth token is created for the user and written to Redis with a TTL of 300
- The auth token is sent back to the user via SMS as a URL they can auth at

When an auth token is presented:
- The auth token is looked up in redis
- If not found, 401
- If found, it includes a user ID which can be used to look up the user, generate a JWT with limited permissions (only flavor/ingredient management...no profile management. We restrict this grant to users who log in with email/password (more secure)

## Tasks
- [x] Redis added to the docker-compose
- [x] User model get by phone number
- [x] User model generate auth token
- [x] User model get user by auth token
- [x] Handlers
- [x] use ngrok to test everything out end-to-end!
